- name: Create GCE instance
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Create a GCE instance
      google.cloud.gcp_compute_instance:
        name: sama-tz
        zone: asia-southeast1-a
        machine_type: n2-custom-4-16384
        labels:
          goog-ec-src: vm_add-tf
        disks:
          - auto_delete: true
            boot: true
            initialize_params:
              source_image: projects/suse-sap-cloud/global/images/sles-12-sp5-sap-v20241028-x86-64
              disk_size_gb: 40
              disk_type: pd-standard
        network_interfaces:
          - subnetwork: projects/vpc-host-nonprod-406007/regions/asia-southeast1/subnetworks/backend
            stack_type: IPV4_ONLY
        can_ip_forward: false
        deletion_protection: false
        service_accounts:
          - email: 661396101845-compute@developer.gserviceaccount.com
            scopes:
              - https://www.googleapis.com/auth/devstorage.read_only
              - https://www.googleapis.com/auth/logging.write
              - https://www.googleapis.com/auth/monitoring.write
              - https://www.googleapis.com/auth/service.management.readonly
              - https://www.googleapis.com/auth/servicecontrol
              - https://www.googleapis.com/auth/trace.append
        scheduling:
          - automatic_restart: true
            on_host_maintenance: MIGRATE
            preemptible: false
        shielded_instance_config:
          enable_integrity_monitoring: true
          enable_secure_boot: false
          enable_vtpm: true
