---
- name: Create a VM instance in GCP using Ansible
  hosts: localhost
  gather_facts: no
  vars:
    project: "factory-nonprod-project"
    zone: "asia-southeast1-c"
    instance_name: "samayein-tz"
    machine_type: "n2-custom-4-16384"
    source_image: "projects/windows-cloud/global/images/windows-server-2022-dc-v20241115"
    disk_size: 50
    disk_type: "pd-standard"
    subnetwork: "projects/vpc-host-nonprod-406007/regions/asia-southeast1/subnetworks/backend"
    service_account_email: "661396101845-compute@developer.gserviceaccount.com"
  tasks:
    - name: Create a VM instance
      google.cloud.gcp_compute_instance:
        name: "{{ instance_name }}"
        machine_type: "{{ machine_type }}"
        zone: "{{ zone }}"
        project: "{{ project }}"
        disks:
          - auto_delete: true
            boot: true
            initialize_params:
              source_image: "{{ source_image }}"
              disk_size_gb: "{{ disk_size }}"
              disk_type: "{{ disk_type }}"
            device_name: "samayein-tz"
        attached_disks:
          - device_name: "samayein-tz-disk-01"
            mode: "READ_WRITE"
        can_ip_forward: false
        deletion_protection: false
        enable_display: false
        labels:
          goog-ec-src: "vm_add-tf"
        network_interfaces:
          - network: 
              selfLink: "{{ subnetwork }}"
            access_configs:
              - name: "External NAT"
                type: "ONE_TO_ONE_NAT"
        scheduling:
          automatic_restart: true
          on_host_maintenance: "MIGRATE"
          preemptible: false
          provisioning_model: "STANDARD"
        service_accounts:
          - email: "{{ service_account_email }}"
            scopes:
              - "https://www.googleapis.com/auth/devstorage.read_only"
              - "https://www.googleapis.com/auth/logging.write"
              - "https://www.googleapis.com/auth/monitoring.write"
              - "https://www.googleapis.com/auth/service.management.readonly"
              - "https://www.googleapis.com/auth/servicecontrol"
              - "https://www.googleapis.com/auth/trace.append"
        shielded_instance_config:
          enable_integrity_monitoring: true
          enable_secure_boot: false
          enable_vtpm: true

 
