---
- name: Create a VM instance in GCP using Ansible
  hosts: localhost
  gather_facts: no
  vars:
    project: "factory-nonprod-project"
    zone: "asia-southeast1-c"
    instance_name: "samayein-tz"
    machine_type: "n2-custom-4-16384"
    source_image: "projects/windows-cloud/global/images/windows-server-2022-dc-v20241115"
    disk_size: 50
    disk_type: "pd-standard"
    subnetwork: "projects/vpc-host-nonprod-406007/regions/asia-southeast1/subnetworks/backend"
    service_account_email: "661396101845-compute@developer.gserviceaccount.com"
  tasks:
    - name: create boot disk
      google.cloud.gcp_compute_disk:
        name: "samayein-tz-disk-01"
        size_gb: 50
        source_image: "{{ source_image }}"
        zone: "{{ zone }}"
        project: "{{ project }}"
        state: present
      register: disk
    - name: Create a VM instance
      google.cloud.gcp_compute_instance:
        name: "{{ instance_name }}"
        machine_type: "{{ machine_type }}"
        zone: "{{ zone }}"
        project: "{{ project }}"
        disks:
        - auto_delete: true
          boot: true
          source: "{{ disk }}"
          initialize_params:
            disk_type: "{{ disk_type }}"
        labels:
          goog-ec-src: "vm_add-tf"
        network_interfaces:
        - network: "{{ subnetwork }}"
          access_configs:
          - name: "External NAT"
            type: "ONE_TO_ONE_NAT"
 
