---
- name: Create a VM instance in GCP using shared VPC
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Create a VM instance
      google.cloud.gcp_compute_instance:
        name: "samayein-tz"
        machine_type: "n1-standard-1"
        zone: "asia-southeast1-b"
        project: "factory-nonprod-project"
        disks:
          - auto_delete: true
            boot: true
            initialize_params:
              source_image: "projects/ubuntu-os-cloud/global/images/family/ubuntu-2204-lts"
        network_interfaces:
          - network: "projects/vpc-host-nonprod-406007/global/networks/default"
            subnetwork: "projects/vpc-host-nonprod-406007/regions/asia-southeast1/subnetworks/backend"
            access_configs:
              - name: "External NAT"
                type: "ONE_TO_ONE_NAT"
      register: vm
 
