- name: Create GCE instance
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Create a GCE instance
      google.cloud.gcp_compute_instance:
        name: sama-tz
        zone: asia-southeast1-a
        machine_type: n2-custom-4-16384
        disks:
          - auto_delete: true
            boot: true
            initialize_params:
              source_image: projects/suse-sap-cloud/global/images/sles-12-sp5-sap-v20241028-x86-64
              disk_size_gb: 40
              disk_type: pd-standard
        network_interfaces:
          - subnetwork: projects/vpc-host-nonprod-406007/regions/asia-southeast1/subnetworks/backend
            stack_type: IPV4_ONLY
        can_ip_forward: false
        deletion_protection: false

