---
- hosts: all
  collections:
   - community.general
  become: true
  tasks:
    - name: Install Open SCAP
      community.general.zypper:
        name: openscap openscap-utils scap-security-guide
        state: present