---
- hosts: all
  gather_facts: False
  become: true
  tasks:
    - name: Deploy Password Policy
      shell: pam-config -a --cracklib --cracklib-minlen=15 --cracklib-difok=3 --cracklib-lcredit=-1 --cracklib-ucredit=-1 --cracklib-dcredit=-1 --cracklib-ocredit=-1
    
    - name: Deploy Password History
      shell: pam-config -a --pwhistory --pwhistory-remember=5
      
    - name: Deploy auto lock/unlock account in /etc/pam.d/login file
      lineinfile:
        path: /etc/pam.d/login
        line: "auth    required    pam_tally2.so deny=5 unlock_time=600"
        insertafter: EOF
        
    - name: Deploy auto lock/unlock account in /etc/pam.d/sudo file
      lineinfile:
        path: /etc/pam.d/sudo
        line: "auth    required    pam_tally2.so deny=5 unlock_time=600"
        insertafter: EOF
        
    - name: Deploy auto lock/unlock account in /etc/pam.d/gdm file
      lineinfile:
        path: /etc/pam.d/gdm
        line: "auth    required    pam_tally2.so deny=5 unlock_time=600"
        insertafter: EOF
        
    - name: Deploy auto lock/unlock account in /etc/pam.d/sshd file
      lineinfile:
        path: /etc/pam.d/sshd
        line: "auth    required    pam_tally2.so deny=5 unlock_time=600"
        insertafter: EOF
     
    - name: Set Password Maximum Age
      lineinfile:
        create: true
        dest: /etc/login.defs
        regexp: ^#?PASS_MAX_DAYS
        line: PASS_MAX_DAYS 180
        
    - name: Set Password Minimum Age
      lineinfile:
        create: true
        dest: /etc/login.defs
        regexp: ^#?PASS_MIN_DAYS
        line: PASS_MIN_DAYS 1
        
    - name: Set Password Warning Age
      lineinfile:
        dest: /etc/login.defs
        regexp: ^PASS_WARN_AGE *[0-9]*
        state: present
        line: PASS_WARN_AGE 7