- name: Add a new line to my_file.txt
  hosts: suse02-tz
  tasks:
#    - name: Add new line
#      lineinfile:
#        path: /tmp/test
#        line: "Manual Way."
#        insertafter: EOF
#        
    - name: test
      lineinfile:
        path: /tmp/test
        line: "auth    required    pam_tally2.so deny=5 unlock_time=600"
        regexp: "This line will be inserted before the match."