---

- name: Create instance in GCP
  hosts: localhost
  gather_facts: false
  vars:
    project: "factory-nonprod-project"
    disk_name: "test-ansible-disk-01"
    machine_name: "test-ansible"
    region: "asia-southeast1"
    zone: "asia-southeast1-b"
    source_image: "projects/ubuntu-os-cloud/global/images/family/ubuntu-2204-lts"
    disk_size: 20
    machine_type: "f1-micro"

  tasks:
    - name: Create a disk
      google.cloud.gcp_compute_disk:
        name: "{{ disk_name }}"
        size_gb: "{{ disk_size }}"
        source_image: "{{ source_image }}"
        zone: "{{ zone }}"
        project: "{{ project }}"
        auth_kind: serviceaccount
        service_account_file: "{{ service_account_file }}"
        state: present
      register: disk



